using Zebl.Application.Dtos.Patients;
using Zebl.Infrastructure.Persistence.Entities;

namespace Zebl.Api.Mapping;

/// <summary>
/// Maps Patient entity rows to list DTO so Find Patient column keys match API JSON (camelCase).
/// </summary>
public static class PatientListItemMapper
{
    public static PatientListItemDto Map(Patient p) => new()
    {
        PatID = p.PatID,
        PatFirstName = p.PatFirstName,
        PatLastName = p.PatLastName,
        PatMI = p.PatMI,
        PatFullNameCC = p.PatFullNameCC,
        PatDateTimeCreated = p.PatDateTimeCreated,
        PatDateTimeModified = p.PatDateTimeModified,
        CreatedDate = p.PatDateTimeCreated,
        ModifiedDate = p.PatDateTimeModified,
        PatCreatedUserGUID = p.PatCreatedUserGUID,
        PatLastUserGUID = p.PatLastUserGUID,
        PatCreatedUserName = p.PatCreatedUserName,
        PatLastUserName = p.PatLastUserName,
        PatCreatedComputerName = p.PatCreatedComputerName,
        PatLastComputerName = p.PatLastComputerName,
        PatAccountNo = p.PatAccountNo,
        PatActive = p.PatActive,
        PatAddress = p.PatAddress,
        PatAddress2 = p.PatAddress2,
        PatAptReminderPref = p.PatAptReminderPref,
        PatAuthTracking = p.PatAuthTracking,
        PatBillingPhyFID = p.PatBillingPhyFID,
        PatBirthDate = p.PatBirthDate,
        PatBox8Reserved = p.PatBox8Reserved,
        PatBox9bReserved = p.PatBox9bReserved,
        PatBox9cReserved = p.PatBox9cReserved,
        PatCellPhoneNo = p.PatCellPhoneNo,
        PatCellSMTPHost = p.PatCellSMTPHost,
        PatCity = p.PatCity,
        PatClaLibFID = p.PatClaLibFID,
        PatClaimDefaults = p.PatClaimDefaults,
        PatClassification = p.PatClassification,
        PatCoPayAmount = p.PatCoPayAmount,
        PatCoPayPercent = p.PatCoPayPercent,
        PatCustomField1 = p.PatCustomField1,
        PatCustomField2 = p.PatCustomField2,
        PatCustomField3 = p.PatCustomField3,
        PatCustomField4 = p.PatCustomField4,
        PatCustomField5 = p.PatCustomField5,
        PatDiagnosis1 = p.PatDiagnosis1,
        PatDiagnosis2 = p.PatDiagnosis2,
        PatDiagnosis3 = p.PatDiagnosis3,
        PatDiagnosis4 = p.PatDiagnosis4,
        PatDiagnosis5 = p.PatDiagnosis5,
        PatDiagnosis6 = p.PatDiagnosis6,
        PatDiagnosis7 = p.PatDiagnosis7,
        PatDiagnosis8 = p.PatDiagnosis8,
        PatDiagnosis9 = p.PatDiagnosis9,
        PatDiagnosis10 = p.PatDiagnosis10,
        PatDiagnosis11 = p.PatDiagnosis11,
        PatDiagnosis12 = p.PatDiagnosis12,
        PatDontSendPromotions = p.PatDontSendPromotions,
        PatDontSendStatements = p.PatDontSendStatements,
        PatEmergencyContactName = p.PatEmergencyContactName,
        PatEmergencyContactPhoneNo = p.PatEmergencyContactPhoneNo,
        PatEmergencyContactRelation = p.PatEmergencyContactRelation,
        PatEmployed = p.PatEmployed,
        PatExternalFID = p.PatExternalFID,
        PatPaymentMatchingKey = p.PatPaymentMatchingKey,
        PatEZClaimPayConsent = p.PatEZClaimPayConsent,
        PatFacilityPhyFID = p.PatFacilityPhyFID,
        PatFaxNo = p.PatFaxNo,
        PatFirstDateTRIG = p.PatFirstDateTRIG,
        PatHeight = p.PatHeight,
        PatHomePhoneNo = p.PatHomePhoneNo,
        PatInsuredSigOnFile = p.PatInsuredSigOnFile,
        PatLastAppointmentKeptTRIG = p.PatLastAppointmentKeptTRIG,
        PatLastAppointmentNotKeptTRIG = p.PatLastAppointmentNotKeptTRIG,
        PatLastServiceDateTRIG = p.PatLastServiceDateTRIG,
        PatLastCellSMPTHostUpdate = p.PatLastCellSMPTHostUpdate,
        PatLastStatementDateTRIG = p.PatLastStatementDateTRIG,
        PatLastPatPmtDateTRIG = p.PatLastPatPmtDateTRIG,
        PatLocked = p.PatLocked,
        PatMarried = p.PatMarried,
        PatMemberID = p.PatMemberID,
        PatOrderingPhyFID = p.PatOrderingPhyFID,
        PatPhoneNo = p.PatPhoneNo,
        PatPhyPrintDate = p.PatPhyPrintDate,
        PatPriEmail = p.PatPriEmail,
        PatPrintSigDate = p.PatPrintSigDate,
        PatReferringPhyFID = p.PatReferringPhyFID,
        PatRecallDate = p.PatRecallDate,
        PatReminderNote = p.PatReminderNote,
        PatReminderNoteEvent = p.PatReminderNoteEvent,
        PatRenderingPhyFID = p.PatRenderingPhyFID,
        PatResourceWants = p.PatResourceWants,
        PatSecEmail = p.PatSecEmail,
        PatSex = p.PatSex,
        PatSigOnFile = p.PatSigOnFile,
        PatSigSource = p.PatSigSource,
        PatSigText = p.PatSigText,
        PatSSN = p.PatSSN,
        PatState = p.PatState,
        PatStatementAddressLine1 = p.PatStatementAddressLine1,
        PatStatementAddressLine2 = p.PatStatementAddressLine2,
        PatStatementCity = p.PatStatementCity,
        PatStatementName = p.PatStatementName,
        PatStatementMessage = p.PatStatementMessage,
        PatStatementState = p.PatStatementState,
        PatStatementZipCode = p.PatStatementZipCode,
        PatSupervisingPhyFID = p.PatSupervisingPhyFID,
        PatTotalInsBalanceTRIG = p.PatTotalInsBalanceTRIG,
        PatTotalPatBalanceTRIG = p.PatTotalPatBalanceTRIG,
        PatTotalUndisbursedPaymentsTRIG = p.PatTotalUndisbursedPaymentsTRIG,
        PatTotalBalanceCC = p.PatTotalBalanceCC,
        PatWeight = p.PatWeight,
        PatWorkPhoneNo = p.PatWorkPhoneNo,
        PatZip = p.PatZip,
        PatLastPaymentRequestTRIG = p.PatLastPaymentRequestTRIG,
        PatFirstNameTruncatedCC = p.PatFirstNameTruncatedCC,
        PatLastNameTruncatedCC = p.PatLastNameTruncatedCC,
        PatFullNameFMLCC = p.PatFullNameFMLCC,
        PatDiagnosisCodesCC = p.PatDiagnosisCodesCC,
        PatTotalBalanceIncludingUndisbursedPatPmtsCC = p.PatTotalBalanceIncludingUndisbursedPatPmtsCC,
        PatTotalPatBalanceIncludingUndisbursedPatPmtsCC = p.PatTotalPatBalanceIncludingUndisbursedPatPmtsCC,
        PatCityStateZipCC = p.PatCityStateZipCC,
        PatStatementCityStateZipCC = p.PatStatementCityStateZipCC,
        AdditionalColumns = new Dictionary<string, object?>()
    };
}
